### ISSUE TITLE
[Feature] Implement NinjaPhenix's Containter Library for Reinforced Mods?

### ISSUE THREAD

**Issue by aisukuma** [Aton-Kish/reinforced-chests#17]
**Describe the solution you'd like**
Implement this [library by NinjaPhenix](https://www.curseforge.com/minecraft/mc-mods/ninjaphenixs-container-library) to display a simpler inventory screen to the user.

**Additional context**
While I know that players can resize their GUIs in their options menu, but I think it would look cool to see paginated or scrollable containers from your mod. Having to not have the big inventory screens take up screen space would be ideal but not sure if trying to implement NinjaPhenix's library might cause issues.

Though this is a feature request, you don't have to since it would probably require the user to download another mod to make it compatible with your reinforced mods.

**Comment by Aton-Kish** [comment]
This looks good to me.
I'll try it when I have time.

**Comment by MrJorman** [comment]
> This looks good to me. I'll try it when I have time.

really need, please ADD!

**Comment by MrJorman** [comment]
My players have a double chest that goes beyond their screen, and also overlaps REI/NEI/JEI items.

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/178542454-f2f5113d-6c35-4ea3-86c6-6914dd09e72c.png)

**Comment by Aton-Kish** [comment]
Thank you for waiting.
I couldn't use NinjaPhenix's Container Library for various reasons, but I have completed the scroll screen implementation!

https://github.com/Aton-Kish/reinforced-chests#configure

| mod | version |
| --- | --- |
| reinforced chests | v2.1.0+ |
| reinforced shulker boxes | v2.1.0+ |
| reinforced barrels | v2.2.0+ |
