### ISSUE TITLE
No Item Name displayed when hovering over item in chest

### ISSUE THREAD

**Issue by Zethin64** [Aton-Kish/reinforced-chests#2]
When using the new Reinforced Chests, item names are not shown when hovering mouse over an item. 

Example: https://i.imgur.com/nJ63b71.png

![DEMOMOD](https://user-images.githubusercontent.com/85813703/136473626-6fe85863-aa27-4286-a3e6-9b0699e53097.png)

Thank you for the amazing mod! <3

P.S. This last part is more of a feature request than anything else - but it would be really amazing if this was compatible with EasierChests. You can see in the example image that the green sorting/matching item arrows are absent when in these new sexy chests.

**Comment by Aton-Kish** [comment]
Thanks for reporting the bug:)
In [version 1.0.1](https://www.curseforge.com/minecraft/mc-mods/reinforced-chests/files/3484819), fixed mouse over tooltip.

It seems that it is needed to add at least a condition whether your chest screen is a reinforced chest screen or not to the EasierChests code (link below).
https://github.com/gbl/EasierChests/blob/24b1e3fa3e6464060a0beb31840cf1b3b08554a8/src/main/java/de/guntram/mcmod/easierchests/mixins/AbstractContainerScreenMixin.java#L136-L148
So, if you want to enjoy "EasierReinforecedChests", could you please create an issue in the EasierChests repo?

**Comment by Zethin64** [comment]
Awesome <3 Thank you for the quick fix @Aton-Kish! I have submitted a request to EasierChests for compatability as well.
