### ISSUE TITLE
[Bug] Why there is jar inside jar?

### ISSUE THREAD

**Issue by ardissaps** [Aton-Kish/reinforced-chests#24]
It is complicated to do texture pack (i am doing dark mode).

**Comment by Aton-Kish** [comment]
The code and texture image to create the screen are common for each mod, reinforced chests, shulker boxes, and barrels. It's ridiculous to write the same code and image in each mod, so I separated them as a shared library. That is why there is a shared library jar inside each mod jar.

This is not a bug.

**Comment by Aton-Kish** [comment]
I can modify it to create a screen with a vanilla texture (e.g. generic_54.png).
Is it more convenient for you when doing texture pack?

**Comment by ardissaps** [comment]
Using 

> I can modify it to create a screen with a vanilla texture (e.g. generic_54.png). Is it more convenient for you when doing texture pack?

I edit the pack myself as a temporary solution (I did it by extracting whole then repacked it again in zip) as I am using dark mode but the chest does not follow. It would better if use vanilla texture as long as it change alongside Vanilla when using texture pack, so no need to edit anything.

**Comment by Aton-Kish** [comment]
OK, I got it. I'll fix it.

**Comment by Aton-Kish** [comment]
released version 2.0.3+1.19

**Comment by ardissaps** [comment]
> released version 2.0.3+1.19

Would you port the fixe to 1.18.2 too please? Thank you :p

**Comment by Aton-Kish** [comment]
> Would you port the fixe to 1.18.2 too please?

Sorry, I missed this comment.
I ported it to 1.18.2.
