### ISSUE TITLE
[Feature] Add configuration options for size of chests

### ISSUE THREAD

**Issue by mastery3** [Aton-Kish/reinforced-chests#37]
I believe 108 slots is extremely low for the cost of 8 diamonds, so I would like to change the amount of slots provided by the chest.

Also, Netherite Chests should have an advantage other than blast/fire resistance for how expensive they are. A waterlogged Diamond Chest with 4 signs/blocks around it cannot be exploded, and fire resistance only applies to item drops because chests are not flammable. This means Netherite Chests have no meaningful advantage compared to waterlogged Diamond chests.

**Comment by Aton-Kish** [comment]
I haven't considered changing the configuration yet.
If you don't agree with this, please change the recipe by unzipping the mod jar file directly. 

One of the advantages of the netherite variant is that it does not burn down in lava.
This is especially useful with the netherite shulkerbox.

**Comment by mastery3** [comment]
If you can afford a diamond shulker box, you can also afford an ender chest to protect the diamond shulker box and to clear up your inventory, so still not a massive improvement compared to its cost. Also, I specifically mentioned adding a configuration option to _change the number of slots in the reinforced blocks_, not the recipe (which I have already changed with a custom datapack), which requires modification of the mod.

**Comment by Aton-Kish** [comment]
I have no intention of changing the number of slots. So I want you to lower the cost by editing the recipe if you don't agree with its cost.

> I have already changed with a custom datapack

You've already changed it and there's nothing anymore you can do about it.

**Comment by mastery3** [comment]
Changing the default number of slots is a secondary topic and refusing to do so does not warrant closing this issue. I'm asking to allow the user to change the number of slots for themselves in the title, and your replies prove you have not read the title or the comments:

Title: "[Feature] Add **configuration options** for size of chests"
"Also, I specifically mentioned adding a **configuration option** to change the number of slots in the reinforced blocks"

Additionally, I have in fact modified the source code of this mod, and adding a few configuration options to a config that already exists and changing some values isn't a difficult change. As you have refused to properly read my comments and have shown arrogant behavior, there is no point in commenting on this issue.
