### ISSUE TITLE
[Bug] Serverside crash upon startup

### ISSUE THREAD

**Issue by BeatknightProgs** [Aton-Kish/reinforced-chests#42]
### Describe the bug

Starting my server, it just crashes and says the error stems from a nested jar called reinfcore.

### To Reproduce

1. First step: Install all 3 Reinforced Storage mods on a server alongside Fabric API

### Expected behavior

The server starts and does not give a fatal error message.

### Screenshots

[A screenshot of the Log file. Not sure how to display images in MD, sorry. It's been awhile.](https://i.imgur.com/UXbeMCr.png)

### Environment

- Minecraft 1.19.4
- Fabric Loader 0.14.18
- Fabric API 0.76.0

### Logs

[15:38:56] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.18
--
2 | [15:38:56] [ForkJoinPool-1-worker-2/WARN]: Mod terralith uses the version 2.3.7b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '7b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
3 | [15:38:56] [ForkJoinPool-1-worker-3/WARN]: The mod "infinityfix" contains invalid entries in its mod json:
4 | - Unsupported root entry "side" at line 11 column 11
5 | [15:38:56] [main/INFO]: Loading 78 mods:
6 | - axesareweapons 1.6.5
7 | - collective 6.54
8 | - craftable_enchanted_golden_apple 1.0.4
9 | - cryingportals 2.3
10 | - expanded_axe_enchanting 1.0.5
11 | - expanded_trident_enchanting 1.0.5
12 | - fabric-api 0.76.0+1.19.4
13 | \|-- fabric-api-base 0.4.23+9ff28bcef4
14 | \|-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
15 | \|-- fabric-biome-api-v1 13.0.6+348a9c64f4
16 | \|-- fabric-block-api-v1 1.0.5+e022e5d1f4
17 | \|-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
18 | \|-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
19 | \|-- fabric-command-api-v1 1.2.25+f71b366ff4
20 | \|-- fabric-command-api-v2 2.2.4+ae0966baf4
21 | \|-- fabric-commands-v0 0.2.42+df3654b3f4
22 | \|-- fabric-containers-v0 0.1.52+df3654b3f4
23 | \|-- fabric-content-registries-v0 3.5.7+ae0966baf4
24 | \|-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
25 | \|-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
26 | \|-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
27 | \|-- fabric-dimensions-v1 2.1.44+7f87f8faf4
28 | \|-- fabric-entity-events-v1 1.5.12+e45f7c65f4
29 | \|-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
30 | \|-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
31 | \|-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
32 | \|-- fabric-item-api-v1 2.1.16+09a3510cf4
33 | \|-- fabric-item-group-api-v1 3.0.3+043f9acff4
34 | \|-- fabric-key-binding-api-v1 1.0.32+c477957ef4
35 | \|-- fabric-keybindings-v0 0.2.30+df3654b3f4
36 | \|-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
37 | \|-- fabric-loot-api-v2 1.1.25+75e98211f4
38 | \|-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
39 | \|-- fabric-message-api-v1 5.1.0+1ee8be40f4
40 | \|-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
41 | \|-- fabric-models-v0 0.3.29+11ba9c3bf4
42 | \|-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
43 | \|-- fabric-networking-v0 0.3.39+df3654b3f4
44 | \|-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
45 | \|-- fabric-particles-v1 1.0.22+f1e4495bf4
46 | \|-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
47 | \|-- fabric-registry-sync-v0 2.1.2+a383ab97f4
48 | \|-- fabric-renderer-api-v1 2.2.4+81e8c576f4
49 | \|-- fabric-renderer-indigo 1.1.0+81e8c576f4
50 | \|-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
51 | \|-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
52 | \|-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
53 | \|-- fabric-rendering-v0 1.1.40+df3654b3f4
54 | \|-- fabric-rendering-v1 2.1.0+8f878217f4
55 | \|-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
56 | \|-- fabric-resource-loader-v0 0.11.0+938a1d56f4
57 | \|-- fabric-screen-api-v1 1.0.44+8c25edb4f4
58 | \|-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
59 | \|-- fabric-sound-api-v1 1.0.8+75e98211f4
60 | \|-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
61 | \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
62 | - fabric-language-kotlin 1.9.2+kotlin.1.8.10
63 | \|-- org_jetbrains_kotlin_kotlin-reflect 1.8.10
64 | \|-- org_jetbrains_kotlin_kotlin-stdlib 1.8.10
65 | \|-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10
66 | \|-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10
67 | \|-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.0
68 | \|-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
69 | \|-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
70 | \|-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
71 | \|-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
72 | \|-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
73 | \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
74 | - fabricloader 0.14.18
75 | - healthcare 1.2.1
76 | \|-- config2brigadier 1.2.1
77 | \|-- fabric-permissions-api-v0 0.1-SNAPSHOT
78 | \-- server_translations_api 1.4.19+1.19.3
79 | \-- packet_tweaker 0.3.0+1.18.2
80 | - immortalcoral 1.6.3
81 | - infinityfix 1.0.1
82 | - java 17
83 | - minecraft 1.19.4
84 | - naturallychargedcreepers 3.2
85 | - no-shield-delay 1.0.0
86 | \|-- com_electronwill_night-config_core 3.6.5
87 | \-- com_electronwill_night-config_toml 3.6.5
88 | - reinfbarrel 2.3.4+1.19
89 | \-- reinfcore 3.0.6+1.19
90 | \-- cloth-config 10.0.96
91 | \-- cloth-basic-math 0.6.1
92 | - reinfchest 2.3.2+1.19
93 | \-- reinfcore 3.0.6+1.19
94 | \-- cloth-config 10.0.96
95 | \-- cloth-basic-math 0.6.1
96 | - reinfshulker 2.3.2+1.19
97 | \-- reinfcore 3.0.6+1.19
98 | \-- cloth-config 10.0.96
99 | \-- cloth-basic-math 0.6.1
100 | - smallernetherportals 3.4
101 | - terralith 2.3.7b
102 | [15:38:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
103 | [15:38:56] [main/INFO]: Compatibility level set to JAVA_17
104 | [15:39:02] [main/INFO]: Loading Collective version 6.54.
105 | [15:39:02] [main/INFO]: Loaded C2B lib.
106 | [15:39:03] [main/INFO]: Reading config file for no-shield-delay
107 | [15:39:03] [main/INFO]: Enabled: true, Raise Time: 0
108 | [15:39:03] [main/INFO]: Finished Initializing no-shield-delay
109 | [15:39:03] [main/ERROR]: Failed to start the minecraft server
110 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'reinfcore'!
111 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.18.jar:?]
112 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.18.jar:?]
113 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.18.jar:?]
114 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.18.jar:?]
115 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.18.jar:?]
116 | at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
117 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
118 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
119 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.18.jar:?]
120 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.18.jar:?]
121 | Caused by: java.lang.AbstractMethodError: Receiver class fr.catcore.server.translations.api.resource.language.SystemDelegatedLanguage does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_4679(java.lang.String, java.lang.String)' of abstract class net.minecraft.class_2477.
122 | at net.minecraft.class_2477.method_48307(class_2477.java:89) ~[server-intermediary.jar:?]
123 | at net.minecraft.class_2588.method_11025(class_2588.java:55) ~[server-intermediary.jar:?]
124 | at net.minecraft.class_2588.method_27659(class_2588.java:143) ~[server-intermediary.jar:?]
125 | at net.minecraft.class_2561.method_27657(class_2561.java:112) ~[server-intermediary.jar:?]
126 | at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
127 | at net.minecraft.class_2561.getString(class_2561.java:51) ~[server-intermediary.jar:?]
128 | at net.minecraft.class_7706.handler$zfi000$fabric-item-group-api-v1$collect(class_7706.java:2690) ~[server-intermediary.jar:?]
129 | at net.minecraft.class_7706.method_47334(class_7706.java) ~[server-intermediary.jar:?]
130 | at net.minecraft.class_7706.<clinit>(class_7706.java:1896) ~[server-intermediary.jar:?]
131 | at net.fabricmc.fabric.impl.itemgroup.ItemGroupHelper.<clinit>(ItemGroupHelper.java:34) ~[fabric-item-group-api-v1-3.0.3+043f9acff4-50a4958d35b46575.jar:?]
132 | at net.fabricmc.fabric.impl.itemgroup.FabricItemGroupBuilderImpl.method_47324(FabricItemGroupBuilderImpl.java:38) ~[fabric-item-group-api-v1-3.0.3+043f9acff4-50a4958d35b46575.jar:?]
133 | at atonkish.reinfcore.item.ModItemGroup.create(ModItemGroup.java:27) ~[reinfcore-3.0.6+1.19-91bdd08723e54c1f.jar:?]
134 | at atonkish.reinfcore.item.ModItemGroup.<clinit>(ModItemGroup.java:31) ~[reinfcore-3.0.6+1.19-91bdd08723e54c1f.jar:?]
135 | at atonkish.reinfcore.ReinforcedCoreMod.onInitialize(ReinforcedCoreMod.java:27) ~[reinfcore-3.0.6+1.19-91bdd08723e54c1f.jar:?]
136 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.18.jar:?]
137 | ... 7 more

</body>
</html>
``` -->

### Additional context

[15:38:56] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.18
[15:38:56] [ForkJoinPool-1-worker-[2](https://exaroton.com/log/#L2)/WARN]: Mod terralith uses the version 2.[3](https://exaroton.com/log/#L3).7b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '7b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:38:56] [ForkJoinPool-1-worker-3/WARN]: The mod "infinityfix" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 11 column 11
[15:38:56] [main/INFO]: Loading 78 mods:
	- axesareweapons 1.6.5
	- collective 6.5[4](https://exaroton.com/log/#L4)
	- craftable_enchanted_golden_apple 1.0.4
	- cryingportals 2.3
	- expanded_axe_enchanting 1.0.[5](https://exaroton.com/log/#L5)
	- expanded_trident_enchanting 1.0.5
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabric-language-kotlin 1.9.2+kotlin.1.8.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.18
	- healthcare 1.2.1
	   |-- config2brigadier 1.2.1
	   |-- fabric-permissions-api-v0 0.1-SNAPSHOT
	   \-- server_translations_api 1.4.19+1.19.3
	        \-- packet_tweaker 0.3.0+1.18.2
	- immortalcoral 1.6.3
	- infinityfix 1.0.1
	- java 17
	- minecraft 1.19.4
	- naturallychargedcreepers 3.2
	- no-shield-delay 1.0.0
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- reinfbarrel 2.3.4+1.19
	   \-- reinfcore 3.0.6+1.19
	        \-- cloth-config 10.0.96
	             \-- cloth-basic-math 0.6.1
	- reinfchest 2.3.2+1.19
	   \-- reinfcore 3.0.6+1.19
	        \-- cloth-config 10.0.96
	             \-- cloth-basic-math 0.6.1
	- reinfshulker 2.3.2+1.19
	   \-- reinfcore 3.0.6+1.19
	        \-- cloth-config 10.0.96
	             \-- cloth-basic-math 0.6.1
	- smallernetherportals 3.4
	- terralith 2.3.7b
[15:38:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[15:38:5[6](https://exaroton.com/log/#L6)] [main/INFO]: Compatibility level set to JAVA_1[7](https://exaroton.com/log/#L7)
[15:39:02] [main/INFO]: Loading Collective version 6.54.
[15:39:02] [main/INFO]: Loaded C2B lib.
[15:39:03] [main/INFO]: Reading config file for no-shield-delay
[15:39:03] [main/INFO]: Enabled: true, Raise Time: 0
[15:39:03] [main/INFO]: Finished Initializing no-shield-delay
[15:39:03] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'reinfcore'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.1[8](https://exaroton.com/log/#L8).jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:4[9](https://exaroton.com/log/#L9)) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.18.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.18.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.18.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class fr.catcore.server.translations.api.resource.language.SystemDelegatedLanguage does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_4679(java.lang.String, java.lang.String)' of abstract class net.minecraft.class_2477.
	at net.minecraft.class_2477.method_48307(class_2477.java:89) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_1[10](https://exaroton.com/log/#L10)25(class_2588.java:55) ~[server-intermediary.jar:?]
	at net.minecraft.class_2588.method_27659(class_2588.java:143) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.method_27657(class_2561.java:[11](https://exaroton.com/log/#L11)2) ~[server-intermediary.jar:?]
	at net.minecraft.class_5348.getString(class_5348.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2561.getString(class_2561.java:51) ~[server-intermediary.jar:?]
	at net.minecraft.class_7706.handler$zfi000$fabric-item-group-api-v1$collect(class_7706.java:2690) ~[server-intermediary.jar:?]
	at net.minecraft.class_7706.method_47334(class_7706.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_7706.<clinit>(class_7706.java:1896) ~[server-intermediary.jar:?]
	at net.fabricmc.fabric.impl.itemgroup.ItemGroupHelper.<clinit>(ItemGroupHelper.java:34) ~[fabric-item-group-api-v1-3.0.3+043f9acff4-50a4958d35b46575.jar:?]
	at net.fabricmc.fabric.impl.itemgroup.FabricItemGroupBuilderImpl.method_47324(FabricItemGroupBuilderImpl.java:38) ~[fabric-item-group-api-v1-3.0.3+043f9acff4-50a4958d35b46575.jar:?]
	at atonkish.reinfcore.item.ModItemGroup.create(ModItemGroup.java:27) ~[reinfcore-3.0.6+1.19-91bdd08723e54c1f.jar:?]
	at atonkish.reinfcore.item.ModItemGroup.<clinit>(ModItemGroup.java:31) ~[reinfcore-3.0.6+1.19-91bdd08723e54c1f.jar:?]
	at atonkish.reinfcore.ReinforcedCoreMod.onInitialize(ReinforcedCoreMod.java:27) ~[reinfcore-3.0.6+1.19-91bdd08723e54c1f.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.[14](https://exaroton.com/log/#L14).[18](https://exaroton.com/log/#L18).jar:?]
	... 7 more

**Comment by BeatknightProgs** [comment]
I had the forge version of cloth-config installed, so I installed the fabric version (same version) and it still doesn't work

**Comment by Aton-Kish** [comment]
> Caused by: java.lang.AbstractMethodError: Receiver class fr.catcore.server.translations.api.resource.language.SystemDelegatedLanguage does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_4679(java.lang.String, java.lang.String)' of abstract class net.minecraft.class_2477.

It seems that this error was caused by the translation API.

> 78 | -- server_translations_api 1.4.19+1.19.3

Does this server translations API mod support 1.19.4? Judging from its version number, it only supports up to 1.19.3. Even if you uninstall all reinforced storage mods, I think it will still crash.
There have been internal API changes between versions 1.19.3 and 1.19.4, so a version mismatch is likely to cause bugs.

**Comment by Aton-Kish** [comment]
If you still have problems, please re-open this.
