### ISSUE TITLE
[Feature]there needs chest Upgrade Tool

### ISSUE THREAD

**Issue by Plain-Second** [Aton-Kish/reinforced-chests#58]
### Describe the solution you'd like
there needs chest Upgrade Tool
Chests can be upgraded with tools, Normal chests can be upgraded to copper chests by using a one-time copper upgrade item，Iron chests can be upgraded to golden chests by using a one-time golden upgrade item. And so on
### Additional context
In the early stage of survival, there were not so many copper, iron, gold, and diamonds, etc., to build chests, In the later stage, when there are many items that can be used to build chests and use them, it is very troublesome to move the items from the old chests before new chest can be used

**Comment by Aton-Kish** [comment]
Thank you for your suggestion. However, I prefer simple mods and do not wish to create too many things. Therefore, I have no plans to implement this. It is the same as #19.
