### ISSUE TITLE
[Bug] Update from 1.20.4 to 1.20.6/1.21 loose items

### ISSUE THREAD

**Issue by MrBretze** [Aton-Kish/reinforced-chests#67]
### Describe the bug

I have updated to 1.21 and all my of my chest has been "reseted" all stack inside has been set to 1 item

### To Reproduce

1 Minecraft 1.20.4 world with Reinforced Chest

### Screenshots
1.21
![image](https://github.com/user-attachments/assets/6597b61a-c424-430b-9e74-2ddc3c1eebef)

1.20.4
![image](https://github.com/user-attachments/assets/dbe7805d-1b53-4bee-8880-bd8ff4323e80)

### Environment

- Minecraft: 1.21/1.20.4
- Fabric Loader: 0.16.2 / 0.15.11
- Fabric API: 0.102.0+1.21 / 0.97.1+1.20.4

### Additional context
Its a world on Multiplayer

**Comment by MrBretze** [comment]
I have tried with the 1.20.6 version and i have the same issue.

**Comment by MrBretze** [comment]
In my test, Reinforced Barrels and Reinforced Shulker Boxes have the same issue
I guess the problem comes from the conversion from NBT to Component

**Comment by CrossanaVS** [comment]
I think it's the same thing.

**Describe the bug**

1.20 updated to 1.21 and 1.21.1

In every slot in the Reinforced Chest only one item remained (i.e. from 64/30/15 items to 1)
 - if this item was enchanted (tools, weapons, elytra) it was disenchanted in 1.21.
 - i.e. "Enchanted Book: Mending" -> In 1.21 was just an "Enchanted Book" (it was still glowing but it was without specific enchantment).
 - if the item was renamed, it's back to its default name in 1.21.
 - Every Shulker Box (Reinforced or not) in the chest was emptied and renamed ones were back to a default name.

The same bug with the Reinforced Barrels and stand alone Shulker Boxes. If the Reinforced Shulker Box was in a chest (Reinforced or not) it was emptied and renamed to its default name.

**Environment**
Minecraft: 1.21 and 1.21.1/1.20
Fabric Loader: 0.16.5 0.16.2 / 0.14.21 
Fabric API:0.105.0+1.21.1   0.102.0+1.21 / 0.83.0+1.20

**Additional context**
Its a Single Player World.

**Comment by Unariginal** [comment]
I'd like to bump this. Big issue here.. I can't see a part of this mod's code that handles converting stored item data from 1.20.4 to 1.20.5 data components. Tons of our players would have lost their items if we didn't make a backup.

**Comment by Aton-Kish** [comment]
It's getting late. This issue has been resolved in reinforced chests v3.0.1+1.20/v3.1.1+1.12.1, reinforced shulker boxes v3.0.1+1.20/v3.2.1+1.12.1, and reinforced barrels v2.5.1+1.20/v2.6.1+1.12.1. If there are any further issues, please re-open this issue.
